export const usersTypes = {
    IS_LOADING: 'USERS_IS_LOADING',
    LOAD_USERS: 'USERS_LOAD_USERS',
    FIND_USER: 'FIND_USER_WITH_NAME'
}

export const productTypes = {
    IS_LOADING: 'PRODUCT_IS_LOADING',
    LOAD_PRODUCTS: 'LOAD_PRODUCTS',
    LOAD_SINGLE_PRODUCT: 'LOAD_SINGLE_PRODUCT',
    FIND_PRODUCT: 'FIND_PRODUCT'
}

export const postsTypes = {
    LOAD_POSTS: 'POSTS_LOAD_POSTS'
}

